environment:
  global:
    COMPILE: compile
    TEST_COMPILE: test:compile
    TEST_SUITE: test
  matrix:
    - SCALA_VERSION: 2.11.11
    - SCALA_VERSION: 2.12.3

install:
  - ps: |
         Add-Type -AssemblyName System.IO.Compression.FileSystem
         if (!(Test-Path -Path "C:\sbt\sbt-launcher-packaging-0.13.13" )) {
           (new-object System.Net.WebClient).DownloadFile(
              'https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip',
              'C:\sbt-0.13.13.zip'
           )
           [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-0.13.13.zip", "C:\sbt")
         }
  - ps: |
        if (!(Test-Path -Path "C:\Program Files\Java\jdk1.8.0\src.zip")) {
          (new-object System.Net.WebClient).DownloadFile(
            'https://github.com/fommil/openjdk8src/raw/master/src.zip',
            'C:\Program Files\Java\jdk1.8.0\src.zip'
          )
        }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=C:\sbt\sbt-launcher-packaging-0.13.13\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xss2m -Xms1024m -Xmx4096m -XX:+TieredCompilation -XX:+CMSPermGenSweepingEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:MaxPermSize=256m -XX:ReservedCodeCacheSize=256M

build_script: 
  - sbt "; +++ %SCALA_VERSION% %COMPILE%; ++ %SCALA_VERSION% %TEST_COMPILE%"
test_script:
  - sbt "; +++ %SCALA_VERSION% %TEST_SUITE%"
