language: scala
scala:
  - 2.10.4
  - 2.11.5
env:
  global:
  - secure: IgzqZjDGDiXkBrGoTdAdj/em5C+rO48QSdeA3K0FTzuti8VuC4U7RslqiqokF1QziOxA6GYjB0sfVdupAnDmyuYLUjDDvvEuQu73bt1fucQxho2xUHq678xjorV2xKrAKriiFG8i4HMFNVL+vKKtScGTkjyNI29bdLYJS7Bftgw=
rvm:
  - "1.9.3-p392"
before_script:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k $SECRET -in .travis.secrets.enc -d -a -out .travis.secrets; fi'
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then source .travis.secrets; fi'
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm .travis.secrets; fi'
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.email "travis-ci@http4s.org"
- git config --global user.name "Travis CI"
- "cd $TRAVIS_BUILD_DIR/src/jekyll && bundle install && cd -"
script: sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues
after_success: 
- bash bin/travis-publish
webhooks:
  urls:
    - https://webhooks.gitter.im/e/aadbcad1ca1e91b5a189
  on_success: change
  on_failure: always
  on_start: false
