language: scala
scala:
- 2.12.1
- 2.11.8
jdk: oraclejdk8
env:
  global:
  - HUGO_VERSION=0.18
  - LOGBACK_ROOT_LEVEL=OFF
  - SBT_VERSION=0.13.13
before_script:
- mkdir -p $HOME/.sbt/launchers/$SBT_VERSION/
- curl -L -o $HOME/.sbt/launchers/$SBT_VERSION/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar
- mkdir $HOME/bin
- export PATH=$HOME/bin:$PATH
script: bash bin/travis
webhooks:
  urls:
  - https://webhooks.gitter.im/e/aadbcad1ca1e91b5a189
  on_success: change
  on_failure: always
  on_start: false
sudo: false
cache:
  directories:
  - "$HOME/.coursier/cache"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
