baseurl = "http://http4s.org/"
languageCode = "en-us"
title = "http4s"

[params]
# TODO Render these as part of the build process
apiVersion = "0.17"
version = "0.17.0-M1"

[[menu.tut]]
    name = "Scaladoc"
    weight = 10000
    url = "/v0.17/api"
