baseurl = "http://http4s.org/"
languageCode = "en-us"
title = "http4s"

[params]
# TODO Render these as part of the build process
apiVersion = "0.16"
version = "0.16.0-SNAPSHOT"

[[menu.tut]]
    name = "Scaladoc"
    weight = 10000
    url = "/v0.16/api"
